import { Timer, TimerAction } from "@/lib/db/schema";
import { TimerWithActions } from "@/lib/types/timer.type";

export const timerData: Timer = {
  id: "timer-1",
  orderIndex: 0,
  name: "Video + Sound - Landing of the bride and groom",
  scheduledStartTime: new Date(),
  durationMinutes: 3.5,
  status: "PENDING" as const,
  weddingEventId: "wedding-event-test-1",
  createdById: "user-1",
  lastModifiedById: "user-1",
  createdAt: new Date(),
  updatedAt: new Date(),
  isManual: false,
  startedAt: null,
  completedAt: null,
};

export const actionsData: TimerAction[] = [
  {
    id: "action-1",
    timerId: "test-timer",
    type: "SOUND",
    status: "PENDING",
    triggerOffsetMinutes: -4.5,
    title: "",
    url: "/assets/sounds/audio-1-atterrissage-tony.mp3",
    urls: [],
    contentFr: "Contenu en français pour la deuxième action",
    contentEn: "English content for the second action",
    contentBr: "Conteúdo em português para a segunda ação",
    orderIndex: 0,
    displayDurationSec: 10,
    createdAt: new Date(),
    executedAt: null,
  },
  {
    id: "action-2",
    timerId: "test-timer",
    type: "IMAGE",
    status: "PENDING",
    triggerOffsetMinutes: -1.25,
    title: "",
    url: "/assets/images/jeu.png",
    urls: [],
    contentFr: "Contenu en français pour la première action",
    contentEn: "English content for the first action",
    contentBr: "Conteúdo em português para a primeira ação",
    orderIndex: 1,
    displayDurationSec: 10,
    createdAt: new Date(),
    executedAt: null,
  },
  {
    id: "action-3",
    timerId: "test-timer",
    type: "VIDEO",
    status: "PENDING",
    triggerOffsetMinutes: -1,
    title: "Vidéo de clôture",
    url: "/assets/videos/video-demo-with-sound.mp4",
    urls: [],
    contentFr: "Contenu en français pour la troisième action",
    contentEn: "English content for the third action",
    contentBr: "Conteúdo em português para a terceira ação",
    orderIndex: 2,
    displayDurationSec: 10,
    createdAt: new Date(),
    executedAt: null,
  },
  {
    id: "action-4",
    timerId: "test-timer",
    type: "IMAGE_SOUND",
    status: "PENDING",
    triggerOffsetMinutes: -0.5,
    title: "Image finale",
    url: "/assets/images/photomaton.png",
    urls: ["/assets/images/telephone.png", "/assets/sounds/audio-6-telephone.mp3"],
    contentFr: "Contenu en français pour la quatrième action",
    contentEn: "English content for the fourth action",
    contentBr: "Conteúdo em português para a quarta ação",
    orderIndex: 3,
    displayDurationSec: 10,
    createdAt: new Date(),
    executedAt: null,
  },
];

export const timerWithActionsData: TimerWithActions = {
  ...timerData,
  actions: actionsData,
};
